FROM python:3.9-slim-buster
RUN apt-get update && apt-get install -y --no-install-recommends build-essential
WORKDIR /chatgpt-webot
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
